#!/bin/bash
# Author
#    Giorgio Negrini
#
# Script
#    install
#
# Description
#    Installs OpenFOAM-vim extension for OpenFOAM.
#
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1

error() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    exit 1
}

[[ ! $WM_PROJECT = "" ]] || error "No OpenFOAM was found"


# Define the folder where your plugins are stored
#------------------------------------------------------------------------------
[[ ! $VIMFOLDER = "" ]] || VIMFOLDER=$HOME/.vim

# Color definition for nice output and playing with bash
#------------------------------------------------------------------------------
red='\e[0;31m'
green='\e[0;32m'
nc='\e[0m'

# Checking if .vim directories are available and create if bool = false
#------------------------------------------------------------------------------
if [ ! -d $VIMFOLDER ]; then
    mkdir -p $VIMFOLDER
fi

if [ ! -d $VIMFOLDER/syntax ]; then
    mkdir -p $VIMFOLDER/syntax
fi

if [ ! -d $VIMFOLDER/syntax/OpenFOAM ]; then
    mkdir -p $VIMFOLDER/syntax/OpenFOAM
fi

if [ ! -d $VIMFOLDER/indent ]; then
    mkdir -p $VIMFOLDER/indent
fi

if [ ! -d $VIMFOLDER/ftdetect ]; then
    mkdir -p $VIMFOLDER/ftdetect
fi


# COLORS
#------------------------------------------------------------------------------
ORANGE='\033[0;33m'
BORANGE='\033[1;33m'
GREEN='\033[0;36m'
BGREEN='\033[1;36m'
BLUE='\033[0;34m'
BBLUE='\033[1;34m'

# Copy files only if the copied files are newer [-u]
#------------------------------------------------------------------------------
echo -e "\nInstalling OpenFOAM-vim for "$WM_PROJECT-$WM_PROJECT_VERSION"...\n"
cp -r syntax/* $VIMFOLDER/syntax/
cp ftdetect/* $VIMFOLDER/ftdetect/
cp indent/* $VIMFOLDER/indent/
echo -e "\n${ORANGE}You can add custom highlightings in your local version of OpenFOAM-vim:${nc}"
echo -e "    syntax keyword custom<Type>\n    highlight link custom<Type> OpenFOAM_<type>\n\n"


# Function 1 and 2
echo "Functions"
general=$VIMFOLDER/syntax/OpenFOAM/general/general.vim
functions=$(grep -hr " TypeName(" $FOAM_SRC/OpenFOAM/primitives/functions/Function[12]* 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | tr '\n' ' ')
for f in $functions
do
    sed -i "s/__FUNCTIONS12__/\\\\ $f\n    __FUNCTIONS12__/g" $general
done
sed -i "/__FUNCTIONS12__/d" $general

# Boundary conditions
echo "Boundary conditions"
BC=$VIMFOLDER/syntax/OpenFOAM/0/BC.vim
bcs=$(grep -rl "class [a-zA-Z0-9]*FvPatch[A-Za-z]*Field" $FOAM_SRC 2>/dev/null | xargs dirname | awk -F'/' '{print $NF}' | sort | uniq | xargs -I file find $FOAM_SRC -name fileFvPatch*Field.H | xargs grep -h " TypeName(" | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | sed -e "s/FvPatch::typeName_//g" -e "s/^[a-zA-Z0-9]*:://g" | tr '\n' ' ')
for b in $bcs
do
    sed -i "s/__BCS__/\\\\ $b\n    __BCS__/g" $BC
done
sed -i "/__BCS__/d" $BC
# - keywords
bcskeys=$(grep -rl "class [a-zA-Z0-9]*FvPatch[A-Za-z]*Field" $FOAM_SRC 2>/dev/null | xargs dirname | awk -F'/' '{print $NF}' | sort | uniq | xargs -I file find $FOAM_SRC -name fileFvPatch*Field.C | xargs grep [dD]ict | grep -o "\"[a-zA-Z]*\"" | sed "s/\"//g" | sort | uniq | tr '\n' ' ')
for k in $bcskeys
do
    sed -i "s/__BCSKEYS__/\\\\ $k\n    __BCSKEYS__/g" $BC
done
sed -i "/__BCSKEYS__/d" $BC

# Mesh changers
echo "Mesh changers"
DYN=$VIMFOLDER/syntax/OpenFOAM/constant/dynamicMeshDict.vim
ms=$(grep -hr " TypeName(" $FOAM_SRC/dynamicMesh/motionSolvers/ $FOAM_SRC/rigidBody* $FOAM_SRC/sixDoFRigidBody* 2>/dev/null | grep -i Motion | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | tr '\n' ' ')
for m in $ms
do
    sed -i "s/__MS__/\\\\ $m\n    __MS__/g" $DYN
done
sed -i "/__MS__/d" $DYN
sms=$(grep -hr " TypeName(" $FOAM_SRC/dynamicMesh/motionSolvers/ $FOAM_SRC/rigidBody* $FOAM_SRC/sixDoFRigidBody* 2>/dev/null | grep -vi Motion | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' ')
for s in $sms
do
    sed -i "s/__SMS__/\\\\ $s\n    __SMS__/g" $DYN
done
sed -i "/__SMS__/d" $DYN
# - keywords
mckeys=$(find $FOAM_SRC/dynamicMesh/ $FOAM_SRC/rigidBody* $FOAM_SRC/sixDoFRigidBody* -name "*.C" -type f 2>/dev/null | xargs grep -i Dict | grep -v Coeffs | grep -o "\"[a-zA-Z0-9]*\"" | sort | uniq | sed "s/\"//g" | tr '\n' ' ')
for m in $mckeys
do
    sed -i "s/__MCKEYS__/\\\\ $m\n    __MCKEYS__/g" $DYN
done
sed -i "/__MCKEYS__/d" $DYN

# Function objects
echo "Function objects"
CD=$VIMFOLDER/syntax/OpenFOAM/system/controlDict.vim
functions=$(grep -hr " TypeName(" $FOAM_SRC/functionObjects 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' ')
for f in $functions
do
    sed -i "s/__FOS__/\\\\ $f\n    __FOS__/g" $CD
done
sed -i "/__FOS__/d" $CD
# - keywords
fokeys=$(find $FOAM_SRC/functionObjects -name "*.C" -type f 2>/dev/null | xargs grep -i Dict | grep -v Coeffs | grep -o "\"[a-zA-Z0-9]*\"" | sort | uniq | sed "s/\"//g" | tr '\n' ' ')
for f in $fokeys
do
    sed -i "s/__FOKEYS__/\\\\ $f\n    __FOKEYS__/g" $CD
done
sed -i "/__FOKEYS__/d" $CD

# Algebraic solvers
echo "Solvers"
FVS=$VIMFOLDER/syntax/OpenFOAM/system/fvSolution.vim
sol=$(find $FOAM_SRC/OpenFOAM/matrices/lduMatrix/*ers -name "*.H" 2>/dev/null | xargs grep -h " TypeName(" | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' ')
for s in $sol
do
    sed -i "s/__SOL__/\\\\ $s\n    __SOL__/g" $FVS
done
sed -i "/__SOL__/d" $FVS

# Discretization schemes
echo "Discretisation schemes"
FVS=$VIMFOLDER/syntax/OpenFOAM/system/fvSchemes.vim
sch=$(grep -hr " TypeName(" $FOAM_SRC/finiteVolume/finiteVolume/*Schemes $FOAM_SRC/finiteVolume/interpolation/ 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | tr '\n' ' ')
for s in $sch
do
    sed -i "s/__SCH__/\\\\ $s\n    __SCH__/g" $FVS
done
sed -i "/__SCH__/d" $FVS

# Topo sets
echo "Sets"
SFD=$VIMFOLDER/syntax/OpenFOAM/system/setFieldsDict.vim
topo=$(grep -hr " TypeName(" $FOAM_SRC/meshTools/sets/ 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' ')
for t in $topo
do
    sed -i "s/__TS__/\\\\ $t\n    __TS__/g" $SFD
done
sed -i "/__TS__/d" $SFD

# Fv options/models/constraints
echo "Equation sources"
FVO=$VIMFOLDER/syntax/OpenFOAM/constant/fvOptions.vim
fvs=$(grep -hr " TypeName(" $FOAM_SRC/fvConstraints $FOAM_SRC/fvModels $FOMA_SRC/fvOptions 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' ')
for f in $fvs
do
    sed -i "s/__FVO__/\\\\ $f\n    __FVO__/g" $FVO
done
sed -i "/__FVO__/d" $FVO
# - keywords
fvokeys=$(find $FOAM_SRC/fvConstraints $FOAM_SRC/fvModels $FOMA_SRC/fvOptions -name "*.C" -type f 2>/dev/null | xargs grep -i Dict | grep -v Coeffs | grep -o "\"[a-zA-Z0-9]*\"" | sort | uniq | sed "s/\"//g" | tr '\n' ' ')
for f in $fvokeys
do
    sed -i "s/__FVOKEYS__/\\\\ $f\n    __FVOKEYS__/g" $FVO
done
sed -i "/__FVOKEYS__/d" $FVO

# Turbulence models
echo "Momentum models"
MT=$VIMFOLDER/syntax/OpenFOAM/constant/momentumTransport.vim
mtm=$(echo $(simpleFoam -listMomentumTransportModels 2>/dev/null | grep "^[a-zA-Z]*$" | sed /^$/d | tr '\n' ' ') $(simpleFoam -listTurbulenceModels 2>/dev/null | grep "^[a-zA-Z]*$" | sed /^$/d | tr '\n' ' '))
mtm=$(echo $mtm $(grep -hr " TypeName(" $(find $FOAM_SRC -wholename *laminar/Stokes 2>/dev/null | xargs dirname) 2>/dev/null | sed -e "s/TypeName//g" -e "s/[\"(); ]//g" | sort | uniq | tr '\n' ' '))
for m in $mtm
do
    sed -i "s/__TT__/\\\\ $m\n    __TT__/g" $MT
done
sed -i "/__TT__/d" $MT
# - keywords and subdictionaries
for m in $mtm
do
    mfolder=$(find $FOAM_SRC -name $m)
    mtmkeys=$(grep -i Dict $mfolder/*.C 2>/dev/null | grep -v Coeffs | grep -o "\"[a-zA-Z0-9]*\"" | sort | uniq | sed "s/\"//g" | tr '\n' ' ')
    for mk in $mtmkeys
    do
        sed -i "s/__TTKEYS__/\\\\ $mk\n    __TTKEYS__/g" $MT
    done
done
sed -i "/__TTKEYS__/d" $MT


echo -e "\n\nLook at beginning of the following files to insert custom:"
echo "    - fields:                         ~/.vim/syntax/OpenFOAM/general/variables.vim"
echo "    - boundary conditons:             ~/.vim/syntax/OpenFOAM/0/BC.vim"
echo "    - mesh changers:                  ~/.vim/syntax/OpenFOAM/constant/dynamicMeshDict.vim"
echo "    - function objects:               ~/.vim/syntax/OpenFOAM/system/controlDict.vim"
echo "    - extrude models:                 ~/.vim/syntax/OpenFOAM/system/blockMeshDict.vim"
echo "    - fvOptions/Models/Constraints:   ~/.vim/syntax/OpenFOAM/constant/fvOptions.vim"
echo "    - turbulence/viscosity models:    ~/.vim/syntax/OpenFOAM/constant/momentumTransport.vim"


#------------------------------------------------------------------------------
echo -e "\n\n${nc}
The package is now ready to use! Just open an OpenFOAM file!

${BBLUE}OpenFOAM-vim${nc} by ${BORANGE}Giorgio Negrini${nc}

Credits to ${BGREEN}F. Leinbach${nc} and ${BGREEN}T. Holzmann${nc} for the original extension
-->  https://bitbucket.org/shor-ty/vimextensionopenfoam/src/master/  <--
"


#------------------------------------------------------------------------------
